services:
  ## container for client, calls Dockerfile in client
  client:
    build:
      context: ./client
    container_name: ecommerce-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host